# PostgreSQL
[postgres]
DB = "allocation"
HOST = "localhost"
PORT = 5432
DRIVER = "psycopg"

# Uvicorn
[uvicorn]
HOST = "0.0.0.0"
PORT = 9999

# SQLAlchemy
[sqla]
ECHO = false
ECHO_POOL = false
POOL_SIZE = 30
MAX_OVERFLOW = 20

# Logs
[logs]
# Can be set to "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
LEVEL = "DEBUG"